language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
    - master
    - release

before_script:
  - npm install -g @angular/cli
  - npm install -g sonarqube-scanner
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng lint
  - ng test --watch=false
  - sonar-scanner
    -Dsonar.projectKey=launc-frontend
    -Dsonar.sources=.
    -Dsonar.host.url=http://dev.launc.space:9000
    -Dsonar.login=897c497cfc87d8bbf4b72bc1c1cfd95804aa9c48

addons:
  ssh_known_hosts:
    - launc.space
    - dev.launc.space

before_deploy:
  - openssl aes-256-cbc -K $encrypted_29e790ce9544_key -iv $encrypted_29e790ce9544_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh accept http://dev.api.launc.space \
            && ssh -t launc@dev.launc.space "bash docker/deploy_accept.sh"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh release http://api.launc.space \
            && ssh -t launc@launc.space "bash docker/deploy_prod.sh"
    on:
      branch: release
