language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
    - master
    - release

before_script:
  - npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng lint
  - ng test --watch=false

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh latest
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh release
    on:
      branch: release

