# This defines our starting point
FROM node:latest

RUN mkdir /usr/src/app 
 
WORKDIR /usr/src/app

RUN npm install -g @angular/cli 

COPY . .

ENTRYPOINT npm install && ng serve --port 4200 --host 0.0.0.0